### ISSUE TITLE
Couple of errors when opening RPC Calls page

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-dapps-status#128]
![screenshot from 2016-05-09 14 27 17](https://cloud.githubusercontent.com/assets/581548/15113032/2c9d66da-15f2-11e6-90f1-f057863dc980.png)

**Comment by jacogr** [comment]
@tomusdrw Could you check if this is still valid, added the propTypes in a previous PR.

**Comment by tomusdrw** [comment]
Looks it's fixed now.
