### ISSUE TITLE
Refactor `Calls` to simplify hovering logic.

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity-dapps-status#152]

**Comment by goldylucks** [comment]
Thoughts when developing this:
1. I moved the toolbar outside of each individual "call" element to escape the `overflow: hidden/auto/scroll` trap
2. It's possible to escape the trap using `position: fixed` on the toolbar tho need to handle scrolling while hovering and it feels hacky
3. Another solution could b to try a custom scrollbar that doesn't use overflow

**Comment by goldylucks** [comment]
@jacogr what's your take on this?

**Comment by jacogr** [comment]
I cannot fault the way it has been split up, makes sense. The passing elements around (both Call & Calls to CallToolbar) doesn't feel very clean, I guess we have consensus there. 

Currently though, I don't have any better ideas from 2 & 3 mentioned above, would love to get rid of the element interrogation inside the component and via CSS does seem more 'correct'.

**Comment by tomusdrw** [comment]
I can live with what we have after @jacogr - maybe there will be some better solution possible (or required) later.
