### ISSUE TITLE
rpc calls - actions broken

### ISSUE THREAD

**Issue by goldylucks** [ethcore/parity-dapps-status#164]
@jacogr maybe it got broken in the refactor?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6963212/15517004/bf3cd4f8-21f5-11e6-8ad4-4fc408b8542f.gif)

**Comment by jacogr** [comment]
Sadly, I think you are right, I must have broken this one. Ok, on it.

**Comment by jacogr** [comment]
Sorry about this, PR to fix the wrong naming of variables - replicating & verifying tests outstanding.
